lib/elixir_jobs_web/router.ex
defmodule ElixirJobsWeb.Router do
  use ElixirJobsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug ElixirJobsWeb.Plugs.GuardianPipeline
  end

  pipeline :authentication_required do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElixirJobsWeb do
    # Use the default browser stack
    pipe_through :browser

    get "/", OfferController, :index
    get "/about", PageController, :about
    get "/sponsors", PageController, :sponsors
    get "/rss", OfferController, :rss
    get "/sitemap.xml", SitemapController, :sitemap
    get "/page/:page", OfferController, :index, as: :offer_page
    get "/search", OfferController, :search
    get "/offers/filter/:filter", OfferController, :index_filtered
    get "/offers/place/:filter", OfferController, :index_filtered
    get "/offers/new", OfferController, :new
    post "/offers/new", OfferController, :create
    post "/offers/preview", OfferController, :preview
    put "/offers/preview", OfferController, :preview
    get "/offers/:slug", OfferController, :show

    get "/login", AuthController, :new
    post "/login", AuthController, :create
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", ElixirJobsWeb do
    # Use the default browser stack
    pipe_through [:browser, :authentication_required]

    get "/logout", AuthController, :delete

    scope "/admin", Admin, as: :admin do
      get "/offers/published", OfferController, :index_published
      get "/offers/pending", OfferController, :index_unpublished
      get "/offers/:slug/publish", OfferController, :publish
      get "/offers/:slug/send_twitter", OfferController, :send_twitter
      get "/offers/:slug/send_telegram", OfferController, :send_telegram
      get "/offers/:slug/edit", OfferController, :edit
      put "/offers/:slug/edit", OfferController, :update
      delete "/offers/:slug", OfferController, :delete
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirJobsWeb do
  #   pipe_through :api
  # end
end

lib/elixir_jobs_web/views/layout_view.ex
defmodule ElixirJobsWeb.LayoutView do
  use ElixirJobsWeb, :view

  import Phoenix.Controller, only: [current_url: 1]

  alias ElixirJobsWeb.MicrodataHelper
  alias ElixirJobsWeb.SeoHelper
  alias ElixirJobsWeb.Telegram

  def get_flash_messages(%Plug.Conn{} = conn) do
    conn
    |> Phoenix.Controller.get_flash()
    |> Map.values()
  end

  def get_telegram_channel, do: Telegram.get_channel()
end

lib/elixir_jobs_web/templates/layout/shared/_alerts.html.eex
<%= for message <- get_flash_messages(@conn) do %>
<div class="notification is-primary">
  <span class="delete">&times;</span>
  <%= raw(message) %>
</div>
<% end %>

lib/elixir_jobs_web/templates/layout/shared/_analytics.html.eex
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script defer src="https://www.googletagmanager.com/gtag/js?id=UA-106824960-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', '<%= Application.get_env(:elixir_jobs, :analytics_id) %>');
</script>

lib/elixir_jobs_web/templates/layout/shared/_cookies.html.eex
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js" defer></script>
<script defer>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#5c18bf",
      "text": "#fff"
    },
    "button": {
      "background": "#b842e1",
      "text": "#fff"
    }
  },
  "position": "bottom-right",
  "content": {
    "message": "<%= gettext("By using this website, you allow us to use some cookies to improve your experience and provide statistics") %>"
  }
})});
</script>

lib/elixir_jobs_web/templates/layout/shared/_footer.html.eex
<footer class="footer">
  <div class="container">
    <div class="columns is-desktop">
      <div class="column has-text-centered has-text-left-desktop">
        <p class="section-title">
          <strong>
            <%= raw gettext("ElixirJobs.net &copy %{year}", year: DateTime.utc_now.year) %>
          </strong>
        </p>
        <p>
          <%= link(gettext("Post a job offer"), to: offer_path(@conn, :new)) %>
          |
          <%= link(gettext("About"), to: page_path(@conn, :about)) %>
          |
          <%= link(gettext("Contact us"), to: "mailto:hi@elixirjobs.net") %>
        </p>
        <p>
          <%= link(gettext("On site jobs"), to: offer_path(@conn, :index_filtered, "onsite")) %>
          |
          <%= link(gettext("Remote jobs"), to: offer_path(@conn, :index_filtered, "remote")) %>
        </p>
        <p>
          <%= link(gettext("Full time jobs"), to: offer_path(@conn, :index_filtered, "full_time")) %>
          |
          <%= link(gettext("Part time jobs"), to: offer_path(@conn, :index_filtered, "part_time")) %>
          |
          <%= link(gettext("Freelance jobs"), to: offer_path(@conn, :index_filtered, "freelance")) %>
        </p>
      </div>
      <div class="column has-text-centered has-text-right-desktop">
        <p class="section-title">
          <strong>
            <%= raw gettext("ElixirJobs is sponsored by", year: DateTime.utc_now.year) %>
          </strong>
        </p>
        <p>
          <a href="https://learn-elixir.dev/?utm_source=Elixir_Jobs&utm_medium=r&utm_campaign=s&utm_id=1">
            <%= img_tag(static_path(@conn, "/images/sponsors/learn-elixir-white.svg"), alt: "Learn Elixir", width: 200) %>
          </a>
        </p>
      </div>
    </div>
  </div>
</footer>

lib/elixir_jobs_web/templates/layout/shared/_head.html.eex
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= gettext("Elixir Jobs") %> - <%= SeoHelper.page_title(@conn) %></title>
    <meta name="description" content="<%= SeoHelper.page_description(@conn) %>">
    <meta name="keywords" content="elixir,jobs,community,job,board,phoenix,positions,junior,senior,full time,part time,freelance,contract,publish">
    <meta property="og:url" content="<%= current_url(@conn) %>" />
    <meta property="og:title" content="<%= gettext("Elixir Jobs") %> - <%= SeoHelper.page_title(@conn) %>" />
    <meta property="og:description" content="<%= SeoHelper.page_description(@conn) %>" />
    <meta property="og:image" content="<%= static_url(@conn, "/images/logo.png") %>" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@jobs_elixir" />
    <meta name="twitter:title" content="<%= gettext("Elixir Jobs") %> - <%= SeoHelper.page_title(@conn) %>" />
    <meta name="twitter:description" content="<%= SeoHelper.page_description(@conn) %>" />
    <meta name="twitter:image" content="<%= static_url(@conn, "/images/logo.png") %>" />
    <meta name="application-name" content="<%= gettext("Elixir Jobs") %>">
    <meta name="apple-mobile-web-app-title" content="<%= gettext("Elixir Jobs") %>">
    <meta name="theme-color" content="#ffffff">
    <meta name="msapplication-TileColor" content="#5c18bf">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= static_path(@conn, "/icons/apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= static_path(@conn, "/icons/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= static_path(@conn, "/icons/favicon-16x16.png") %>">
    <link rel="mask-icon" href="<%= static_path(@conn, "/icons/safari-pinned-tab.svg") %>" color="#5c18bf">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#5c18bf">
    <meta name="theme-color" content="#ffffff">
    <link rel="alternate" type="application/rss+xml" title="Elixir Jobs - RSS" href="<%= offer_path(@conn, :rss) %>" />
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

lib/elixir_jobs_web/templates/layout/shared/_hero.html.eex
<section class="hero main is-info is-medium is-bold">
  <div class="hero-body particles-container">
    <div class="container has-text-centered">
      <h1 class="title">
        <%= gettext("Connect with jobs that matter") %>
      </h1>
      <h2 class="subtitle">
        <%= gettext("With Elixir Jobs you can find your next Elixir job directly on your feed.") %>
      </h2>
      <%= link(gettext("Post a job offer!"), to: offer_path(@conn, :new), class: "button new-offer-btn is-primary is-large") %>
    </div>
    <div id="particles"></div>
  </div>
</section>

lib/elixir_jobs_web/templates/layout/shared/_navbar.html.eex
<nav id="navbar" class="navbar is-fixed-top is-primary">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="<%= offer_path(@conn, :index) %>">
        <%= img_tag static_path(@conn, "/images/logo.svg"), class: "logo" %>
        <%= gettext("Elixir Jobs") %>
      </a>
      <span class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navbarMenu" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="<%= offer_path(@conn, :new) %>"><%= gettext "Publish an offer" %></a>
        <a class="navbar-item" href="<%= page_path(@conn, :about) %>"><%= gettext "About" %></a>
      </div>
      <div class="navbar-end">
        <%= if user_logged_in?(@conn) do %>
        <%= link(gettext("Pending offers"), to: admin_offer_path(@conn, :index_unpublished), class: "navbar-item")%>
        <%= link(gettext("Published offers"), to: admin_offer_path(@conn, :index_published), class: "navbar-item")%>
        <%= link(gettext("Log out"), to: auth_path(@conn, :delete), class: "navbar-item") %>
        <% end %>
        <a class="navbar-item" href="<%= "https://t.me/#{Telegram.get_channel()}" %>" target="_blank">
          <i class="fab fa-telegram-plane"></i><span class="is-hidden-desktop">&nbsp;&nbsp;Telegram</span>
        </a>
        <a class="navbar-item" href="https://twitter.com/jobs_elixir" target="_blank">
          <i class="fab fa-twitter"></i><span class="is-hidden-desktop">&nbsp;&nbsp;Twitter</span>
        </a>
        <a class="navbar-item" href="<%= offer_path(@conn, :rss) %>">
          <i class="fa fa-rss"></i><span class="is-hidden-desktop">&nbsp;&nbsp;RSS feed</span>
        </a>
      </div>
    </div>
  </div>
</nav>