lib/elixir_jobs_web/router.ex
defmodule ElixirJobsWeb.Router do
  use ElixirJobsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug ElixirJobsWeb.Plugs.GuardianPipeline
  end

  pipeline :authentication_required do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ElixirJobsWeb do
    # Use the default browser stack
    pipe_through :browser

    get "/", OfferController, :index
    get "/about", PageController, :about
    get "/sponsors", PageController, :sponsors
    get "/rss", OfferController, :rss
    get "/sitemap.xml", SitemapController, :sitemap
    get "/page/:page", OfferController, :index, as: :offer_page
    get "/search", OfferController, :search
    get "/offers/filter/:filter", OfferController, :index_filtered
    get "/offers/place/:filter", OfferController, :index_filtered
    get "/offers/new", OfferController, :new
    post "/offers/new", OfferController, :create
    post "/offers/preview", OfferController, :preview
    put "/offers/preview", OfferController, :preview
    get "/offers/:slug", OfferController, :show

    get "/login", AuthController, :new
    post "/login", AuthController, :create
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", ElixirJobsWeb do
    # Use the default browser stack
    pipe_through [:browser, :authentication_required]

    get "/logout", AuthController, :delete

    scope "/admin", Admin, as: :admin do
      get "/offers/published", OfferController, :index_published
      get "/offers/pending", OfferController, :index_unpublished
      get "/offers/:slug/publish", OfferController, :publish
      get "/offers/:slug/send_twitter", OfferController, :send_twitter
      get "/offers/:slug/send_telegram", OfferController, :send_telegram
      get "/offers/:slug/edit", OfferController, :edit
      put "/offers/:slug/edit", OfferController, :update
      delete "/offers/:slug", OfferController, :delete
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirJobsWeb do
  #   pipe_through :api
  # end
end

lib/elixir_jobs_web/controllers/sitemap_controller.ex
defmodule ElixirJobsWeb.SitemapController do
  use ElixirJobsWeb, :controller

  alias ElixirJobs.Core

  @items_per_page Application.compile_env!(:elixir_jobs, :items_per_page)

  def sitemap(conn, _params) do
    offers = Core.list_offers(published: true)

    total_pages =
      offers
      |> length()
      |> Kernel./(@items_per_page)
      |> Float.ceil()
      |> round()

    render(conn, "sitemap.xml", total_pages: total_pages, offers: offers)
  end
end

lib/elixir_jobs_web/views/sitemap_view.ex
defmodule ElixirJobsWeb.SitemapView do
  use ElixirJobsWeb, :view
end

lib/elixir_jobs_web/templates/sitemap/sitemap.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url>
    <loc><%= offer_url(@conn, :index) %></loc>
    <changefreq>daily</changefreq>
    <priority>1.00</priority>
  </url>
  <%= for filter <- ["onsite", "remote", "full_time", "part_time", "freelance"] do %>
  <url>
    <loc><%= offer_url(@conn, :index_filtered, filter) %></loc>
    <changefreq>daily</changefreq>
    <priority>0.95</priority>
  </url>
  <% end %>
  <url>
    <loc><%= offer_url(@conn, :new) %></loc>
    <priority>0.80</priority>
  </url>
  <url>
    <loc><%= page_url(@conn, :about) %></loc>
    <priority>0.80</priority>
  </url>
  <%= for page <- (1..@total_pages) do %>
  <url>
    <loc><%= offer_url(@conn, :index, page: page) %></loc>
    <changefreq>daily</changefreq>
    <priority>0.70</priority>
  </url>
  <% end %>

  <%= for offer <- @offers do %>
  <url>
    <loc><%= offer_url(@conn, :show, offer.slug) %></loc>
    <changefreq>daily</changefreq>
    <priority>0.90</priority>
  </url>
  <% end %>
</urlset>